[Profile]
ID=WS
Version=9
[Telnet3270]
HostName=192.168.240.1
HostPortNumber=51004
Security=N
CertSelection=AUTOSELECT
[Communication]
Link=telnet3270
[3270]
QueryReplyMode=Auto
HostCodePage=037-Z
[Keyboard]
CuaKeyboard=1
Language=Brazil(275)
DefaultKeyboard=C:\Users\evandrorenan\Documents\PCOMM\teclado.kmp
IBMDefaultKeyboard=N
[LastExitView]
A=4 66 6 896 582 87 13 26 400 0 IBM3270— 37
[Window]
ViewFlags=CF00
RuleLinePos=0 0
